/**
 * Authentica one-time-code delivery.
 *
 * Authentica is the regional provider that actually places a sign-in code on a
 * Saudi handset, over WhatsApp with the account-level SMS fallback behind it.
 * It deliberately never becomes the identity provider: the code it carries is
 * generated by Supabase Auth and verified there too, so a delivery outage can
 * never mint a session. That is why this client exposes sending only, even
 * though the vendor also offers a verification endpoint — a second verifier
 * would be a second source of truth for who is signed in.
 */

export const authenticaOtpChannels = ["whatsapp", "sms", "email"] as const;

export type AuthenticaOtpChannel = (typeof authenticaOtpChannels)[number];

export const authenticaDefaultBaseUrl = "https://api.authentica.sa/api/v2";

export interface AuthenticaOtpProviderOptions {
  readonly apiKey: string;
  readonly baseUrl?: string;
  readonly requestTimeoutMilliseconds?: number;
  readonly fetch?: typeof globalThis.fetch;
}

export interface AuthenticaSendOtpInput {
  readonly method: AuthenticaOtpChannel;
  /** Code generated by the identity provider, forwarded verbatim. */
  readonly otp: string;
  /** Authentica template, whose channel must match `method`. */
  readonly templateId?: number;
  /** International format, including the leading `+`. */
  readonly phone?: string;
  readonly email?: string;
  readonly fallbackPhone?: string;
  readonly fallbackEmail?: string;
}

/**
 * A delivery attempt that did not reach Authentica's accepted state.
 *
 * `retryable` separates a transport or provider-side fault, where resending
 * the same code is reasonable, from a rejected request, where retrying only
 * spends balance. The message never carries the recipient or the code.
 */
export class AuthenticaError extends Error {
  public constructor(
    public readonly providerCode: string,
    public readonly retryable: boolean,
    public readonly httpStatus?: number,
    options?: ErrorOptions,
  ) {
    super("Authentica could not accept the one-time code.", options);
    this.name = "AuthenticaError";
  }
}

export class AuthenticaOtpProvider {
  private readonly fetch: typeof globalThis.fetch;
  private readonly timeoutMilliseconds: number;
  private readonly baseUrl: string;

  public constructor(private readonly options: AuthenticaOtpProviderOptions) {
    this.fetch = options.fetch ?? globalThis.fetch;
    this.timeoutMilliseconds = options.requestTimeoutMilliseconds ?? 10_000;
    this.baseUrl = (options.baseUrl ?? authenticaDefaultBaseUrl).replace(
      /\/+$/,
      "",
    );
  }

  public async sendOtp(input: AuthenticaSendOtpInput): Promise<void> {
    // Serialized before the request is attempted, so a payload this client
    // knows is undeliverable is reported as such instead of being reclassified
    // as a transport fault by the catch below.
    const requestBody = JSON.stringify(payload(input));
    const controller = new AbortController();
    const timeout = setTimeout(
      () => controller.abort(),
      this.timeoutMilliseconds,
    );
    let response: Response;
    let body: unknown;
    try {
      response = await this.fetch(`${this.baseUrl}/send-otp`, {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          "X-Authorization": this.options.apiKey,
        },
        body: requestBody,
        signal: controller.signal,
      });
      body = await readJson(response);
    } catch (error) {
      const timedOut = controller.signal.aborted;
      throw new AuthenticaError(
        timedOut ? "PROVIDER_TIMEOUT" : "PROVIDER_NETWORK_ERROR",
        true,
        undefined,
        { cause: error },
      );
    } finally {
      clearTimeout(timeout);
    }

    if (!response.ok) {
      throw new AuthenticaError(
        statusCode(response.status),
        isRetryableStatus(response.status),
        response.status,
      );
    }

    // Authentica answers 200 with an envelope, so a transport-level success is
    // not on its own an accepted send.
    if (!accepted(body)) {
      throw new AuthenticaError("PROVIDER_REJECTED", false, response.status);
    }
  }
}

export function validateAuthenticaSendOtpInput(
  input: AuthenticaSendOtpInput,
): void {
  if (!/^\d{4,10}$/.test(input.otp)) {
    throw new AuthenticaError("PROVIDER_OTP_INVALID", false);
  }
  const needsPhone = input.method === "sms" || input.method === "whatsapp";
  if (needsPhone && !input.phone) {
    throw new AuthenticaError("PROVIDER_RECIPIENT_MISSING", false);
  }
  if (input.method === "email" && !input.email) {
    throw new AuthenticaError("PROVIDER_RECIPIENT_MISSING", false);
  }
}

function payload(input: AuthenticaSendOtpInput): Record<string, unknown> {
  validateAuthenticaSendOtpInput(input);
  return {
    method: input.method,
    otp: input.otp,
    ...(input.templateId === undefined
      ? {}
      : { template_id: input.templateId }),
    ...(input.phone ? { phone: input.phone } : {}),
    ...(input.email ? { email: input.email } : {}),
    ...(input.fallbackPhone ? { fallback_phone: input.fallbackPhone } : {}),
    ...(input.fallbackEmail ? { fallback_email: input.fallbackEmail } : {}),
  };
}

function accepted(body: unknown): boolean {
  if (typeof body !== "object" || body === null) return false;
  const success = (body as { success?: unknown }).success;
  return success === true || success === "true";
}

function statusCode(status: number): string {
  if (status === 401 || status === 403) return "PROVIDER_UNAUTHORIZED";
  if (status === 402) return "PROVIDER_BALANCE_EXHAUSTED";
  if (status === 429) return "PROVIDER_RATE_LIMITED";
  if (status >= 500) return "PROVIDER_UNAVAILABLE";
  return "PROVIDER_REQUEST_REJECTED";
}

/**
 * A rejected request is the provider's verdict on this payload and repeating
 * it changes nothing; an exhausted balance is operator-fixable but not
 * self-healing, so neither is worth a retry.
 */
function isRetryableStatus(status: number): boolean {
  return status === 429 || status >= 500;
}

async function readJson(response: Response): Promise<unknown> {
  try {
    return await response.json();
  } catch {
    return undefined;
  }
}
